### ISSUE TITLE
Release of Preprocess data and evaluation scripts

### ISSUE THREAD

**Issue by aashusri** [Siwensun/Neural_Diffeomorphic_Flow--NDF#1]
Thank you for your great work. Could you please tell when you will be able to release the preprocess data and evaluation scripts?

**Comment by Siwensun** [comment]
Sorry for the delay. But I have been busy with two conferences' rebuttals this month. We will get it ready before the CVPR conference, which is June 18.

**Comment by Siwensun** [comment]
In terms of preprocess data script, we are basically the same as DeepSDF. But we will release the preprocessed data here.
