### ISSUE TITLE
poor reconstruction results on brain surfaces

### ISSUE THREAD

**Issue by aakash-saboo** [Siwensun/Neural_Diffeomorphic_Flow--NDF#4]
Hello! Thank you so much for your repo. Its really useful.

I trained the model on the pancreas and brain surfaces (with the same config as the pancreas). I am able to reconstruct the pancreas, but the results on brain surfaces are abnormally poor(image attached).

![image](https://github.com/Siwensun/Neural_Diffeomorphic_Flow--NDF/assets/39874883/cb250361-baab-444b-9658-370814f34f1d)

the template learned looks like this.
![image](https://github.com/Siwensun/Neural_Diffeomorphic_Flow--NDF/assets/39874883/b488c060-0682-46fd-bbb0-a39b018a8aea)

the training loss is quite low  of the order of 7x10^-4 (lower than the pancreas dataset with loss as 3x10^-3).

is there anything I am missing with the new dataset while reconstructing?

any help is appreciated.

Thanks
Aakash

**Comment by Siwensun** [comment]
Sorry for the late replay. It is a very interesting question. 

We also found our method, or, in general, global latent code conditioned neural fields, cannot represent very delicate structures, such as cortical surface. To improve the reconstruction performance on complex shapes, you can try some other more local conditional variables:

1. Dense Condition [1]
2. Triplane Condition [2], [3]
3. Point cloud condition [4]

or the other neural representation, such as [5].

[1] DeepCSR: A 3D Deep Learning Approach for Cortical Surface Reconstruction
[2] Hybrid Neural Diffeomorphic Flow for Shape Representation and Generation via Triplane
[3] 3D Neural Field Generation using Triplane Diffusion
[4] Diffusion-SDF: Conditional Generative Modeling of Signed Distance Functions
[5] Hybrid-CSR: Coupling Explicit and Implicit Shape Representation for Cortical Surface Reconstruction

**Comment by aakash-saboo** [comment]
Hey. Thanks for your response.
I tried a lot and yes, the method doesn't work on cortical surfaces at all. The figure 1, with non-smooth surface, is actually the result of low reconstruction resolution. If we increase the resolution, then the reconstruction is smooth.
Even after increasing the resolution, it is not able to capture the cortical folds at all.
I am exploring other methods like the one you suggested.

Thanks again for your response.

Aakash
